### ISSUE TITLE
Bug bei Tagsuche

### ISSUE THREAD

**Issue by ghost** [cRYPTOR1337/Post-User---Filter#3]
Wenn man aus Spaß einen Tag sucht, der rausgefiltert wird, generiert man einfach nur API-Anfragen, aus denen alle Tags gefiltert werden.

Evntl. Filter bei der Suche abstellen?

**Comment by cRYPTOR1337** [comment]
Danke für die Rückmeldung!
Allerdings kann ich dies nicht reproduzieren -> 'repost' als Filter und wenn ich dann repost suche kommt ein 'NICHTS GEFUNDEN ¯_(ツ)_/¯'.
Benutzt du die späteste Version?

**Comment by cRYPTOR1337** [comment]
Habe es jetzt erstmal bei der Suche deaktiviert.
